name: gh-pages-deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: "temurin"
          java-version: "11"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.2.0
        with:
          flutter-version: "2.8.1"
      - name: Deploy to GitHub Pages
        uses: jeremynac/flutter-gh-pages@beta
