name: gh-pages-deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup Java
        uses: actions/setup-java@v3.3.0
        with:
          distribution: "temurin"
          java-version: "11"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.4.0
        with:
          flutter-version: "3.0.3"
      - name: Deploy to GitHub Pages
        uses: jeremynac/flutter-gh-pages@beta
