name: gh-pages-deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Java
        uses: actions/setup-java@v2.1.0
        with:
          distribution: "adopt"
          java-version: "11"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: "2.2.3"
      - name: Deploy to GitHub Pages
        uses: erickzanardo/flutter-gh-pages@v2
